# Generated by Django 4.2.16 on 2024-09-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('is_driver', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=200)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('lang', models.CharField(blank=True, max_length=2, null=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
