# Generated by Django 4.2.16 on 2024-09-06 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_driver_exitreason'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BotUser',
        ),
    ]
