# Generated by Django 4.2.16 on 2024-09-06 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_delete_botuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exitreason',
            name='detailed_reason',
        ),
    ]
